// Central de relatórios: filtros explícitos, detalhe auditável e saída para impressão.
import { useEffect, useState, type KeyboardEvent } from "react";
import { api, mensagemErro, type DashboardExecutivo, type RelatorioClienteItem, type RelatorioComprasCliente, type RelatorioVendasAnalitico, type RelatorioComprasAnalitico, type RelatorioEstoqueAnalitico } from "../api/client";
import { fmtMoney } from "../ui/format";
import { Badge, Button, Card, EmptyRow, ErrorState, Field, Input, Loading, PageHeader, Select, StatCard, Table, TBody, THead, Cell } from "../ui/ui";

type Aba = "dashboard" | "vendas" | "compras" | "estoque" | "financeiro" | "clientes";
const ABAS: { key: Aba; label: string }[] = [
  { key: "dashboard", label: "Dashboard" }, { key: "vendas", label: "Vendas" }, { key: "compras", label: "Compras" },
  { key: "estoque", label: "Estoque" }, { key: "financeiro", label: "Financeiro / DRE" }, { key: "clientes", label: "Clientes" },
];

function isoHoje() { return new Date().toISOString().slice(0, 10); }
function isoInicioMes() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`; }
function queryString(params: Record<string, unknown>) { const query = new URLSearchParams(); Object.entries(params).forEach(([key, value]) => { if (value !== undefined && value !== null && value !== "") query.set(key, String(value)); }); return query.toString(); }
function abrirImpressao(path: string, params: Record<string, unknown>) { const query = queryString(params); window.open(`${path}${query ? `?${query}` : ""}`, "_blank", "noopener,noreferrer"); }
async function baixarArquivo(blob: Blob, nome: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = nome; anchor.click(); URL.revokeObjectURL(url); }

export function Relatorios() {
  const [aba, setAba] = useState<Aba>("dashboard"); const [dash, setDash] = useState<DashboardExecutivo | null>(null); const [carregando, setCarregando] = useState(true); const [erro, setErro] = useState<string | null>(null);
  const [inicio, setInicio] = useState(isoInicioMes); const [fim, setFim] = useState(isoHoje);
  const chaveRelatorio = aba === "vendas" ? "vendas.analitico" : aba === "compras" ? "compras.analitico" : aba === "estoque" ? "estoque.analitico" : aba;
  const saida = async (formato: "csv" | "xlsx") => { try { await baixarArquivo(await api.exportarRelatorio(chaveRelatorio, { data_inicio: inicio, data_fim: fim, formato }), `relatorio-${chaveRelatorio}.${formato}`); } catch (error) { setErro(mensagemErro(error)); } };
  const carregarDashboard = async () => { setCarregando(true); setErro(null); try { setDash(await api.dashboardExecutivo(inicio, fim)); } catch (error) { setDash(null); setErro(mensagemErro(error)); } finally { setCarregando(false); } };
  useEffect(() => { if (aba === "dashboard") void carregarDashboard(); }, [aba]);
  const mudarAbaComTeclado = (event: KeyboardEvent<HTMLButtonElement>, index: number) => { if (!["ArrowRight", "ArrowLeft", "Home", "End"].includes(event.key)) return; event.preventDefault(); const next = event.key === "Home" ? 0 : event.key === "End" ? ABAS.length - 1 : (index + (event.key === "ArrowRight" ? 1 : -1) + ABAS.length) % ABAS.length; setAba(ABAS[next].key); document.getElementById(`relatorio-tab-${ABAS[next].key}`)?.focus(); };
  return <div className="space-y-4">
    <PageHeader contexto="Gestão · Indicadores" title="Relatórios" subtitle="Consulte, investigue e imprima os fatos que formam os indicadores" actions={<div className="flex flex-wrap gap-2"><Button type="button" variant="secondary" size="sm" onClick={() => void carregarDashboard()} disabled={carregando}>Atualizar</Button>{aba !== "clientes" ? <><Button type="button" variant="secondary" size="sm" onClick={() => abrirImpressao("/relatorios/imprimir", { relatorio: chaveRelatorio, data_inicio: inicio, data_fim: fim })}>Imprimir / PDF</Button><Button type="button" variant="secondary" size="sm" onClick={() => void saida("csv")}>CSV</Button><Button type="button" variant="secondary" size="sm" onClick={() => void saida("xlsx")}>XLSX</Button></> : null}</div>} />
    <Card className="p-3"><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><Field label="Data inicial"><Input type="date" value={inicio} onChange={(event) => setInicio(event.target.value)} /></Field><Field label="Data final"><Input type="date" value={fim} onChange={(event) => setFim(event.target.value)} /></Field><Button type="button" onClick={() => void carregarDashboard()} disabled={!inicio || !fim || carregando}>Aplicar período</Button></div><p className="mt-2 text-xs text-slate-500">O período aplicado aparece na impressão e na exportação. Para estoque, a posição é atual até que o relatório histórico seja selecionado.</p></Card>
    <div role="tablist" aria-label="Relatórios por área" className="flex gap-1 overflow-x-auto border-b border-slate-200">{ABAS.map((item, index) => <button key={item.key} id={`relatorio-tab-${item.key}`} type="button" role="tab" aria-selected={aba === item.key} aria-controls="relatorio-panel" tabIndex={aba === item.key ? 0 : -1} onClick={() => setAba(item.key)} onKeyDown={(event) => mudarAbaComTeclado(event, index)} className={`whitespace-nowrap border-b-2 px-3 py-2.5 text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500/50 focus-visible:ring-offset-1 ${aba === item.key ? "border-brand-600 text-brand-700" : "border-transparent text-slate-500 hover:border-slate-300 hover:text-slate-800"}`}>{item.label}</button>)}</div>
    <div id="relatorio-panel" role="tabpanel" aria-label={ABAS.find((item) => item.key === aba)?.label} tabIndex={0} className="focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500/30">
      {aba === "dashboard" ? <Dashboard dash={dash} carregando={carregando} erro={erro} onRetry={carregarDashboard} /> : null}{aba === "vendas" ? <Vendas inicio={inicio} fim={fim} /> : null}{aba === "compras" ? <Compras inicio={inicio} fim={fim} /> : null}{aba === "estoque" ? <Estoque /> : null}{aba === "financeiro" ? <Financeiro inicio={inicio} fim={fim} /> : null}{aba === "clientes" ? <Clientes inicio={inicio} fim={fim} /> : null}
    </div>
  </div>;
}

function Dashboard({ dash, carregando, erro, onRetry }: { dash: DashboardExecutivo | null; carregando: boolean; erro: string | null; onRetry: () => Promise<void> }) { if (carregando) return <Loading message="Carregando indicadores..." />; if (erro || !dash) return <ErrorState message={erro ?? "Nenhum indicador disponível."} onRetry={() => void onRetry()} />; return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-base font-semibold text-slate-900">Resumo executivo</h2><p className="text-sm text-slate-500">Use os números para localizar a exceção e corrija o fato no módulo de origem.</p></div><Badge tone="blue">Período aplicado</Badge></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5"><StatCard label="Pedidos" value={String(dash.kpis.pedidos)} /><StatCard label="Receita líquida" value={fmtMoney(dash.kpis.receita_liquida)} tone="highlight" /><StatCard label="CMV" value={fmtMoney(dash.kpis.cmv)} /><StatCard label="Margem" value={`${dash.kpis.margem_pct}%`} tone="success" /><StatCard label="Ticket médio" value={fmtMoney(dash.kpis.ticket_medio)} /><StatCard label="Caixa" value={fmtMoney(dash.kpis.caixa)} tone="highlight" /><StatCard label="Inadimplência" value={fmtMoney(dash.kpis.inadimplencia)} tone="danger" /><StatCard label="Estoque valorizado" value={fmtMoney(dash.kpis.estoque_valorizado)} /><StatCard label="Compras em aberto" value={fmtMoney(dash.kpis.compras_abertas)} /><StatCard label="Desconto" value={fmtMoney(dash.kpis.desconto)} /></div></div>; }

function Vendas({ inicio, fim }: { inicio: string; fim: string }) {
  const [relatorio, setRelatorio] = useState<RelatorioVendasAnalitico | null>(null); const [ag, setAg] = useState("produto"); const [erro, setErro] = useState<string | null>(null);
  const carregar = async () => { setRelatorio(null); setErro(null); try { setRelatorio(await api.relatorioVendasAnalitico({ agrupamento: ag, data_inicio: inicio, data_fim: fim, limit: 50, offset: 0 })); } catch (error) { setErro(mensagemErro(error)); } };
  useEffect(() => { void carregar(); }, [ag, inicio, fim]);
  return <div className="space-y-3"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-base font-semibold text-slate-900">Vendas analíticas</h2><p className="text-sm text-slate-500">Valores brutos, descontos, CMV e margem por dimensão.</p></div><label className="text-xs font-semibold text-slate-600">Agrupar por<Select value={ag} onChange={(e) => setAg(e.target.value)} className="mt-1 min-w-44" aria-label="Agrupamento de vendas"><option value="produto">Produto</option><option value="categoria">Categoria</option><option value="marca">Marca</option><option value="cliente">Cliente</option><option value="segmento">Segmento</option><option value="vendedor">Vendedor</option><option value="deposito">Depósito</option><option value="canal">Canal</option><option value="condicao">Condição</option></Select></label></div>{relatorio ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><StatCard label="Pedidos" value={String(relatorio.resumo.pedidos)} /><StatCard label="Clientes" value={String(relatorio.resumo.clientes)} /><StatCard label="Receita líquida" value={fmtMoney(relatorio.resumo.receita_liquida)} tone="highlight" /><StatCard label="Margem" value={fmtMoney(relatorio.resumo.receita_liquida - relatorio.resumo.cmv)} tone="success" /></div> : null}{relatorio === null && !erro ? <Loading message="Carregando vendas..." /> : null}{erro ? <ErrorState message={erro} onRetry={() => void carregar()} /> : null}{relatorio ? <Table><THead cols={[relatorio.dimensao, "Qtd.", "Pedidos", "Clientes", "Receita líquida", "CMV", "Margem", "Margem %"]} /><TBody>{relatorio.itens.length ? relatorio.itens.map((r, i) => <tr key={`${String(r.dimensao_id)}-${i}`}><Cell>{r.dimensao || "Não informado"}</Cell><Cell>{r.quantidade}</Cell><Cell>{r.pedidos}</Cell><Cell>{r.clientes}</Cell><Cell>{fmtMoney(r.receita_liquida)}</Cell><Cell>{fmtMoney(r.cmv)}</Cell><Cell className="font-medium">{fmtMoney(r.margem_bruta)}</Cell><Cell>{r.margem_pct}%</Cell></tr>) : <EmptyRow colSpan={8} message="Nenhuma venda no período selecionado." />}</TBody></Table> : null}</div>;
}

function Compras({ inicio, fim }: { inicio: string; fim: string }) {
  const [relatorio, setRelatorio] = useState<RelatorioComprasAnalitico | null>(null); const [erro, setErro] = useState<string | null>(null);
  const carregar = async () => { setRelatorio(null); setErro(null); try { setRelatorio(await api.relatorioComprasAnalitico({ data_inicio: inicio, data_fim: fim, limit: 50, offset: 0 })); } catch (error) { setErro(mensagemErro(error)); } };
  useEffect(() => { void carregar(); }, [inicio, fim]);
  if (erro) return <ErrorState message={erro} onRetry={() => void carregar()} />; if (!relatorio) return <Loading message="Carregando compras..." />;
  return <div className="space-y-3"><div><h2 className="text-base font-semibold text-slate-900">Compras analíticas</h2><p className="text-sm text-slate-500">Pedido, fornecedor, prazo prometido, recebimento parcial e saldo pendente.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><StatCard label="Pedidos" value={String(relatorio.resumo.pedidos)} /><StatCard label="Valor pedido" value={fmtMoney(relatorio.resumo.valor_pedido)} /><StatCard label="Valor recebido" value={fmtMoney(relatorio.resumo.valor_recebido)} tone="highlight" /><StatCard label="Qtd. pendente" value={String(relatorio.resumo.quantidade_pendente)} tone={relatorio.resumo.quantidade_pendente ? "danger" : "success"} /></div><Table><THead cols={["Pedido", "Data", "Fornecedor", "Produto", "Status", "Qtd. pedida", "Qtd. recebida", "Pendente", "Valor"]} /><TBody>{relatorio.itens.length ? relatorio.itens.map((item) => <tr key={item.pedido_item_id}><Cell>{item.numero}</Cell><Cell>{item.data_pedido}</Cell><Cell>{item.fornecedor_nome}</Cell><Cell>{item.produto_nome}<span className="block text-xs text-slate-500">{item.sku || "Sem SKU"}</span></Cell><Cell>{item.status}</Cell><Cell>{item.quantidade_pedida}</Cell><Cell>{item.quantidade_recebida}</Cell><Cell className={item.quantidade_pendente > 0 ? "font-semibold text-amber-700" : ""}>{item.quantidade_pendente}</Cell><Cell>{fmtMoney(item.valor_pedido)}</Cell></tr>) : <EmptyRow colSpan={9} message="Nenhuma compra no período selecionado." />}</TBody></Table></div>;
}

function Estoque() {
  const [relatorio, setRelatorio] = useState<RelatorioEstoqueAnalitico | null>(null); const [erro, setErro] = useState<string | null>(null);
  const carregar = async () => { setRelatorio(null); setErro(null); try { setRelatorio(await api.relatorioEstoqueAnalitico({ limit: 50, offset: 0 })); } catch (error) { setErro(mensagemErro(error)); } };
  useEffect(() => { void carregar(); }, []);
  if (erro) return <ErrorState message={erro} onRetry={() => void carregar()} />; if (!relatorio) return <Loading message="Carregando estoque..." />;
  const rupturas = relatorio.itens.filter((item) => item.situacao === "ruptura").length;
  return <div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-base font-semibold text-slate-900">Posição de estoque</h2><p className="text-sm text-slate-500">Inclui produtos ativos sem saldo e separa ruptura, excesso e reposição.</p></div><Badge tone={rupturas ? "red" : "green"}>{rupturas} em ruptura nesta página</Badge></div><Table><THead cols={["SKU", "Produto", "Depósito", "ABC/XYZ", "Qtd.", "Disponível", "Valor", "Situação"]} /><TBody>{relatorio.itens.length ? relatorio.itens.map((item) => <tr key={`${item.produto_id}-${item.deposito_id}`}><Cell>{item.sku}</Cell><Cell>{item.nome}</Cell><Cell>{item.deposito_nome}</Cell><Cell>{item.classe_abc || "C"}/{item.classe_xyz || "-"}</Cell><Cell>{item.quantidade}</Cell><Cell>{item.disponivel}</Cell><Cell>{fmtMoney(item.valor)}</Cell><Cell><Badge tone={item.situacao === "ruptura" ? "red" : item.situacao === "reposicao" ? "amber" : item.situacao === "excesso" ? "blue" : "green"}>{item.situacao}</Badge></Cell></tr>) : <EmptyRow colSpan={8} message="Nenhuma posição encontrada." />}</TBody></Table></div>;
}

function Financeiro({ inicio, fim }: { inicio: string; fim: string }) { const [r, setR] = useState<{ fluxo_caixa: { entradas: number; saidas: number }; aging: { a_vencer: number; vencido: number }; dre: { receita_liquida: number; cmv: number; lucro_bruto: number } } | null>(null); const [erro, setErro] = useState<string | null>(null); const carregar = async () => { setR(null); setErro(null); try { setR(await api.relatorioFinanceiro(inicio, fim)); } catch (error) { setErro(mensagemErro(error)); } }; useEffect(() => { void carregar(); }, [inicio, fim]); if (erro) return <ErrorState message={erro} onRetry={() => void carregar()} />; if (!r) return <Loading message="Carregando financeiro..." />; return <div className="space-y-3"><div><h2 className="text-base font-semibold text-slate-900">Financeiro e DRE</h2><p className="text-sm text-slate-500">Resumo gerencial. A DRE analítica e o aging detalhado fazem parte da próxima vertical.</p></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><StatCard label="Fluxo de caixa" value={`+${fmtMoney(r.fluxo_caixa.entradas)} / -${fmtMoney(r.fluxo_caixa.saidas)}`} /><StatCard label="Aging a receber" value={`Vencido ${fmtMoney(r.aging.vencido)}`} tone={r.aging.vencido ? "danger" : "success"} sub={`A vencer ${fmtMoney(r.aging.a_vencer)}`} /><StatCard label="Lucro bruto" value={fmtMoney(r.dre.lucro_bruto)} tone="highlight" sub={`Receita ${fmtMoney(r.dre.receita_liquida)} · CMV ${fmtMoney(r.dre.cmv)}`} /></div></div>; }

function Clientes({ inicio, fim }: { inicio: string; fim: string }) {
  const [q, setQ] = useState(""); const [tipo, setTipo] = useState(""); const [segmento, setSegmento] = useState(""); const [categoria, setCategoria] = useState(""); const [mes, setMes] = useState(""); const [semCompraDias, setSemCompraDias] = useState(""); const [filtros, setFiltros] = useState<Record<string, unknown>>({ data_inicio: inicio, data_fim: fim });
  const [rows, setRows] = useState<RelatorioClienteItem[] | null>(null); const [total, setTotal] = useState(0); const [erro, setErro] = useState<string | null>(null); const [selecionado, setSelecionado] = useState<number | null>(null); const [compras, setCompras] = useState<RelatorioComprasCliente | null>(null); const [erroCompras, setErroCompras] = useState<string | null>(null);
  const pesquisar = () => { const next: Record<string, unknown> = { q, tipo_pessoa: tipo, segmento, categoria, sem_compra_dias: semCompraDias, data_inicio: inicio, data_fim: fim, limit: 50, offset: 0 }; if (mes) { const year = new Date().getFullYear(); next.aniversario_inicio = `${year}-${mes}-01`; next.aniversario_fim = `${year}-${mes}-${new Date(year, Number(mes), 0).getDate()}`; } setFiltros(next); setSelecionado(null); setCompras(null); };
  const carregar = async () => { setRows(null); setErro(null); try { const data = await api.relatorioClientes(filtros); setRows(data.itens); setTotal(data.paginacao.total); } catch (error) { setErro(mensagemErro(error)); } }; useEffect(() => { void carregar(); }, [filtros]);
  const abrirCompras = async (cliente: RelatorioClienteItem) => { setSelecionado(cliente.id); setCompras(null); setErroCompras(null); try { setCompras(await api.relatorioComprasCliente(cliente.id, { data_inicio: inicio, data_fim: fim })); } catch (error) { setErroCompras(mensagemErro(error)); } };
  const exportar = async (formato: "csv" | "xlsx") => { try { await baixarArquivo(await api.exportarRelatorioClientes({ ...filtros, formato }), `clientes-${new Date().toISOString().slice(0, 10)}.${formato}`); } catch (error) { setErro(mensagemErro(error)); } };
  return <div className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-base font-semibold text-slate-900">Clientes e relacionamento</h2><p className="text-sm text-slate-500">Filtre a carteira por perfil, aniversário e recência de compra.</p></div><div className="flex flex-wrap gap-2"><Button type="button" variant="secondary" size="sm" onClick={() => abrirImpressao("/relatorios/clientes/imprimir", filtros)}>Imprimir / PDF</Button><Button type="button" variant="secondary" size="sm" onClick={() => void exportar("csv")}>Exportar CSV</Button><Button type="button" variant="secondary" size="sm" onClick={() => void exportar("xlsx")}>Exportar XLSX</Button></div></div>
    <Card className="p-3"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><Field label="Busca"><Input value={q} onChange={(event) => setQ(event.target.value)} placeholder="Nome, documento ou e-mail" onKeyDown={(event) => { if (event.key === "Enter") pesquisar(); }} /></Field><Field label="Tipo"><Select value={tipo} onChange={(event) => setTipo(event.target.value)}><option value="">Todos</option><option value="f">Pessoa física</option><option value="j">Pessoa jurídica</option></Select></Field><Field label="Segmento"><Select value={segmento} onChange={(event) => setSegmento(event.target.value)}><option value="">Todos</option><option value="consumidor_final">Consumidor final</option><option value="profissional">Profissional</option><option value="construtora">Construtora</option><option value="revenda">Revenda</option><option value="varejo">Varejo</option></Select></Field><Field label="Categoria"><Input value={categoria} onChange={(event) => setCategoria(event.target.value)} placeholder="Eletricista, lojista..." /></Field><Field label="Aniversário"><Select value={mes} onChange={(event) => setMes(event.target.value)}><option value="">Qualquer mês</option>{Array.from({ length: 12 }, (_, index) => <option key={index + 1} value={String(index + 1).padStart(2, "0")}>{String(index + 1).padStart(2, "0")}</option>)}</Select></Field><Field label="Sem compra há"><Input type="number" min="1" value={semCompraDias} onChange={(event) => setSemCompraDias(event.target.value)} placeholder="dias" /></Field></div><div className="mt-3 flex justify-end"><Button type="button" onClick={pesquisar}>Pesquisar clientes</Button></div></Card>
    {rows === null && !erro ? <Loading message="Consultando clientes..." /> : null}{erro ? <ErrorState message={erro} onRetry={() => void carregar()} /> : null}{rows ? <><div className="flex items-center justify-between text-sm text-slate-600"><span>{total} cliente(s) encontrado(s)</span><Badge tone="blue">Analítico</Badge></div><Table><THead cols={["Nome", "Tipo", "Segmento", "Categoria", "Cidade/UF", "Última compra", "Ações"]} /><TBody>{rows.length ? rows.map((cliente) => <tr key={cliente.id}><Cell><span className="font-semibold text-slate-900">{cliente.nome}</span><span className="block text-xs text-slate-500">{cliente.doc || "Documento não informado"}</span></Cell><Cell>{cliente.tipo_pessoa === "f" ? "PF" : "PJ"}</Cell><Cell>{cliente.segmento || "-"}</Cell><Cell>{cliente.categoria || "-"}</Cell><Cell>{cliente.cidade || "-"}/{cliente.uf || "-"}</Cell><Cell>{cliente.ultima_compra || "Sem compra"}</Cell><Cell><Button type="button" variant="outline" size="sm" onClick={() => void abrirCompras(cliente)}>Compras</Button></Cell></tr>) : <EmptyRow colSpan={7} message="Nenhum cliente encontrado. Ajuste os filtros ou cadastre a data de nascimento." />}</TBody></Table></> : null}
    {selecionado ? <Card className="p-4">{erroCompras ? <ErrorState message={erroCompras} onRetry={() => { const row = rows?.find((item) => item.id === selecionado); if (row) void abrirCompras(row); }} /> : null}{!erroCompras && !compras ? <Loading message="Carregando histórico de compras..." /> : null}{compras ? <><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">Compras de {compras.cliente.nome}</h3><p className="text-sm text-slate-500">{compras.periodo.inicio} a {compras.periodo.fim} · {compras.paginacao.total} item(ns)</p></div><div className="flex gap-2"><Button type="button" variant="secondary" size="sm" onClick={() => abrirImpressao(`/relatorios/clientes/${selecionado}/compras/imprimir`, { data_inicio: inicio, data_fim: fim })}>Imprimir / PDF</Button><Button type="button" variant="secondary" size="sm" onClick={async () => { try { await baixarArquivo(await api.exportarComprasCliente(selecionado, { data_inicio: inicio, data_fim: fim, formato: "xlsx" }), `cliente-${selecionado}-compras.xlsx`); } catch (error) { setErroCompras(mensagemErro(error)); } }}>Exportar XLSX</Button></div></div><div className="my-3 grid grid-cols-3 gap-3"><StatCard label="Pedidos" value={String(compras.resumo.pedidos)} /><StatCard label="Receita bruta" value={fmtMoney(compras.resumo.receita_bruta)} /><StatCard label="Receita líquida" value={fmtMoney(compras.resumo.receita_liquida)} tone="highlight" /></div><Table><THead cols={["Pedido", "Data", "Produto", "SKU", "Qtd.", "Preço", "Total"]} /><TBody>{compras.itens.length ? compras.itens.map((item, index) => <tr key={`${item.orcamento_id}-${index}`}><Cell>{item.numero}</Cell><Cell>{item.data_venda}</Cell><Cell>{item.nome}</Cell><Cell>{item.sku || "-"}</Cell><Cell>{item.quantidade}</Cell><Cell>{fmtMoney(item.preco_unitario)}</Cell><Cell className="font-medium">{fmtMoney(item.total_item)}</Cell></tr>) : <EmptyRow colSpan={7} message="Nenhuma compra no período." />}</TBody></Table></> : null}</Card> : null}
  </div>;
}

export default Relatorios;
